---
title: "ANA 515 - Assignment 2"
author: alicia saputra
date: "2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Description of the data
##The dataset that I'm using is a US birth dataset
##There are two dataset that is being provided, CDC 1994 - 2003 and SSA 2000 - 2014
##The purpose of this dataset is so that we can see how many baby are born on Friday the 13th compare to any other date
```

```{r setup, include = FALSE}
#Installing my packages
options(repos = list(CRAN="http://cran.rstudio.com/"))
install.packages('readr')
install.packages ('tidyverse')
```

```{r}
#Calling my library
library (readr)
library (tidyverse)
library (knitr)
```

```{r}
#Reading the data
url <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/births/US_births_1994-2003_CDC_NCHS.csv"
cdcdata <- read_csv(url)
spec(cdcdata)

url <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/births/US_births_2000-2014_SSA.csv"
ssadata <- read_csv(url)
spec (ssadata)
```

```{r}
#Clean my data
names(cdcdata[1:5])
## [1] "year"
## [2] "month"
## [3] "date_of_month"
## [4] "day_of_week"
## [5] "births"

#detailed look at my data
head(cdcdata[4:5])
```

```{r}
#Renaming my variables
names(cdcdata[5])
## [5] "births"
renamed <- cdcdata %>%
  rename("Total Births" = "births")
# new name
names(renamed[5:2])
```

```{r}
## Characteristics of the data
# This next chunk is my inline code
```

The CDC birth dataset from 1994 - 2003 has `r ncol(cdcdata)` columns and `r nrow(genderdata)` rows.
The SSA birth dataset from 2000 - 2014 has `r ncol(ssadata)` columns and `r nrow(genderdata2)` rows.

```{r}
#brief description on what each columns measure
text_tbl <- data.frame(
  Names = c("year", "month", "date_of_month", "day_of_week", "births"),
  Description = c(
    "The year of data was recorded",
    "The month of data was recorded", 
    "The date of the month when data was recorded",
    "The day of the week of the date recorded",
    "Total of births")
)
#To check how the table appears, I used the code text_tbl
print (text_tbl)
```

```{r}
##Summary statistics
#Using a new subset named newdata
newdata <- filter(cdcdata,year >=2000, births <=10000)
print (summary (newdata))
```

```{r}
#Using Summary function to find the summary statistics
summary (cdcdata)
summary (ssadata)
```

```{r}
#assigning the result of the summary statistics to a new object
summary_cdc_data <- summary(cdcdata)
summary_ssa_data <- summary (ssadata)

#print my summary
print(summary_cdc_data) 
print (summary_ssa_data)
```

